sudo: false
language: python
cache:
  directories:
    - "$HOME/.cache/pip"
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -e .
  - pip install -U -r dev-requirements.txt
script:
  - py.test
