sudo: false
language: python
cache: pip
matrix:
  include:
    - {env: TOXENV=flake8, python: "3.4"}
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
install:
  - pip install -U pip setuptools
  - pip install tox-travis
script: tox
